import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Providers} from "./providers";
import Nav from "@/components/Navbar";



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className=''>
        <Providers>
          <Nav></Nav>
          <div className='p-5'>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
